services:
  db:
    container_name: postgres_fiber
    image: postgres:16.4
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGHOST: localhost
      PGPORT: 5432
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
